export const ADDON_ID = "storybook/theme-tool";
export const PANEL_ID = `${ADDON_ID}/panel`;
export const PARAM_KEY = "themeTool";

export const EVENTS = {
  CHANGE: `${ADDON_ID}/change`,
  THEME_RESTORE: `${ADDON_ID}/theme-restore`,
};

export const VARIABLE_KEYS = [
  "--oui-font-family",
  "--oui-color-primary",
  "--oui-color-primary-light",
  "--oui-color-primary-darken",
  "--oui-color-primary-contrast",
  "--oui-color-link",
  "--oui-color-link-light",
  "--oui-color-secondary",
  "--oui-color-tertiary",
  "--oui-color-quaternary",
  "--oui-color-danger",
  "--oui-color-danger-light",
  "--oui-color-danger-darken",
  "--oui-color-danger-contrast",
  "--oui-color-success",
  "--oui-color-success-light",
  "--oui-color-success-darken",
  "--oui-color-success-contrast",
  "--oui-color-warning",
  "--oui-color-warning-light",
  "--oui-color-warning-darken",
  "--oui-color-warning-contrast",
  "--oui-color-fill",
  "--oui-color-fill-active",
  "--oui-color-base-1",
  "--oui-color-base-2",
  "--oui-color-base-3",
  "--oui-color-base-4",
  "--oui-color-base-5",
  "--oui-color-base-6",
  "--oui-color-base-7",
  "--oui-color-base-8",
  "--oui-color-base-9",
  "--oui-color-base-10",
  "--oui-color-base-foreground",
  "--oui-color-line",
  "--oui-color-trading-loss",
  "--oui-color-trading-loss-contrast",
  "--oui-color-trading-profit",
  "--oui-color-trading-profit-contrast",
  "--oui-gradient-primary-start",
  "--oui-gradient-primary-end",
  "--oui-gradient-secondary-start",
  "--oui-gradient-secondary-end",
  "--oui-gradient-success-start",
  "--oui-gradient-success-end",
  "--oui-gradient-danger-start",
  "--oui-gradient-danger-end",
  "--oui-gradient-brand-start",
  "--oui-gradient-brand-end",
  "--oui-gradient-brand-stop-start",
  "--oui-gradient-brand-stop-end",
  "--oui-gradient-brand-angle",
  "--oui-gradient-warning-start",
  "--oui-gradient-warning-end",
  "--oui-gradient-neutral-start",
  "--oui-gradient-neutral-end",
  "--oui-rounded-sm",
  "--oui-rounded",
  "--oui-rounded-md",
  "--oui-rounded-lg",
  "--oui-rounded-xl",
  "--oui-rounded-2xl",
  "--oui-rounded-full",
  "--oui-spacing-xs",
  "--oui-spacing-sm",
  "--oui-spacing-md",
  "--oui-spacing-lg",
  "--oui-spacing-xl",
  "--oui-font-size-3xs",
  "--oui-font-size-2xs",
  "--oui-font-size-xs",
  "--oui-font-size-sm",
  "--oui-font-size-base",
  "--oui-font-size-lg",
  "--oui-font-size-xl",
  "--oui-font-size-2xl",
  "--oui-font-size-3xl",
  "--oui-font-size-4xl",
  "--oui-font-size-5xl",
  "--oui-font-size-6xl",
];
