include:
  - project: "orderlynetwork/orderly-fe/common-ci"
    ref: main
    file: "momorepo-release.yaml"
  # - project: "orderlynetwork/orderly-security/orderly-security-templates"
  #   ref: main
  #   file: "npm-security-baseline.yml"

stages:
  - scan
  - check_tag
  - build_docker
  - deploy
  - post-build-audit
  - release

# variables:
#   IMAGE_NAME: "storybook"
#   APP_IMAGE_TAG: "asia-northeast1-docker.pkg.dev/woo-orderly/orderly-network/${IMAGE_NAME}:${$CI_COMMIT_TAG}"
#   ENABLE_PUBLISH: "false"

# workflow:
#   rules:
#     # - if: '($CI_COMMIT_BRANCH =~ /^internal\// || $CI_COMMIT_BRANCH =~ /^pre-release/) && $CI_COMMIT_MESSAGE =~ /publish/'
#     - if: $CI_COMMIT_BRANCH == "cicd-erik"
#       variables:
#         ENABLE_PUBLISH: "true"
#     - when: always

generate-sbom:
  stage: scan
  image:
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-security/syft:v1.43.0
  script:
    - syft ${CI_PROJECT_DIR} -o cyclonedx-json=syft.cdx.json
  artifacts:
    paths:
      - syft.cdx.json
    # reports:
    #   cyclonedx: 
    #     - bom.json
  tags:
    - dev
    - build
  
osv-audit:
  stage: scan
  image: 
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-security/osv-scanner:v2.3.5
  needs: 
    - job: generate-sbom
      artifacts: true
  script:
    - osv-scanner scan -L syft.cdx.json --format=json
    # - osv-scanner scan -L bom.json --format=json --output-file=report.json
  # artifacts:
  #   paths:
  #     - report.json
  #   reports:
  #     sast:
  #       - report.json
  tags:
    - dev
    - build