import { useMemo } from "react";
import {
  RefferalAPI,
  useLocalStorage,
  useRefereeInfo,
} from "@orderly.network/hooks";
import { API } from "@orderly.network/types";
import { modal } from "@orderly.network/ui";
import {
  StatisticsTimeRange,
  useMultiLevelRebateInfo,
  useMultiLevelStatistics,
} from "../../../hooks/useReferralApi";
import { useReferralContext } from "../../../provider";
import { copyText, generateReferralLink } from "../../../utils/utils";
import { EditCodeModal } from "./editCodeModal";
import { EditReferralRate } from "./editReferralRate";

export type ReferralCodeType = RefferalAPI.ReferralCode & {
  isPined?: boolean;
  isAutoGenerated?: boolean;
  referral_type?: "single" | "multi";
  multi_level_statistics?: API.Referral.MultiLevelStatistics;
};

export type ReferralCodesReturns = {
  copyCode: (code: string) => void;
  copyLink: (code: string) => void;
  editRate: (code: ReferralCodeType) => void;
  editCode: (code: ReferralCodeType) => void;
  setPinCode: (code: string, del?: boolean) => void;
  codes?: ReferralCodeType[];
};

export const useReferralCodesScript = (): ReferralCodesReturns => {
  const { referralInfo, referralLinkUrl, mutate, generateCode } =
    useReferralContext();
  const { data: multiLevelRebateInfo } = useMultiLevelRebateInfo();
  const { data: multiLevelStatistics } = useMultiLevelStatistics(
    StatisticsTimeRange.All,
  );
  const [refereesData] = useRefereeInfo({});

  const copyLink = (code: string) => {
    copyText(generateReferralLink(referralLinkUrl, code));
  };
  const copyCode = (code: string) => {
    copyText(code);
  };
  const editRate = (code: ReferralCodeType) => {
    modal.show(EditReferralRate, { code: { ...code }, mutate });
  };

  const editCode = (code: ReferralCodeType) => {
    modal.show(EditCodeModal, {
      code: { ...code },
      successCallback: () => {
        mutate();
      },
    });
  };

  const [pinCodes, setPinCodes] = useLocalStorage<string[]>(
    "orderly_referral_codes",
    [] as string[],
  );
  const setPinCode = (code: string, del?: boolean) => {
    if (del) {
      const index = pinCodes.findIndex((item: string) => item === code);
      if (index !== -1) {
        pinCodes.splice(index, 1);
      }
    } else {
      pinCodes.splice(0, 0, code);
    }

    if (pinCodes.length > 6) {
      pinCodes.splice(pinCodes.length - 1, 1);
    }

    setPinCodes([...pinCodes]);
  };

  const singleLevelTotals = useMemo(() => {
    const totalsMap = new Map<string, { volume: number; commission: number }>();

    if (refereesData) {
      refereesData.forEach((referee) => {
        const code = referee.referral_code;
        if (code) {
          const existing = totalsMap.get(code) || {
            volume: 0,
            commission: 0,
          };
          totalsMap.set(code, {
            volume: existing.volume + (referee.volume || 0),
            commission: existing.commission + (referee.referral_rebate || 0),
          });
        }
      });
    }

    return totalsMap;
  }, [refereesData]);

  const codes = useMemo((): ReferralCodeType[] | undefined => {
    const allCodes: ReferralCodeType[] = [];

    // Add multi-level code if present
    if (multiLevelRebateInfo?.referral_code) {
      const maxRebateRate = multiLevelRebateInfo.max_rebate_rate;
      const defaultRefereeRebateRate =
        multiLevelRebateInfo.default_referee_rebate_rate;
      const referrerRebateRate = Math.max(
        0,
        maxRebateRate - defaultRefereeRebateRate,
      );

      const {
        direct_invites: directInvites,
        indirect_invites: indirectInvites,
        direct_traded: directTraded,
        indirect_traded: indirectTraded,
        direct_volume: directVolume,
        indirect_volume: indirectVolume,
        direct_rebate: directRebate,
        indirect_rebate: indirectRebate,
      } = multiLevelStatistics!;

      const multiLevelCode: ReferralCodeType = {
        code: multiLevelRebateInfo.referral_code ?? "",
        max_rebate_rate: maxRebateRate,
        referee_rebate_rate: defaultRefereeRebateRate,
        referrer_rebate_rate: referrerRebateRate,
        total_invites: directInvites + indirectInvites,
        total_traded: directTraded + indirectTraded,
        total_volume: directVolume + indirectVolume,
        total_rebate: directRebate + indirectRebate,
        referral_type: "multi",
        multi_level_statistics: multiLevelStatistics ?? undefined,
      };

      allCodes.push(multiLevelCode);
    }

    // Add legacy single-level codes
    if (referralInfo?.referrer_info?.referral_codes) {
      const referralCodes: ReferralCodeType[] =
        referralInfo.referrer_info.referral_codes.map((item) => {
          const totals = singleLevelTotals.get(item.code);
          const code: ReferralCodeType = {
            ...item,
            referral_type: "single",
            total_volume: totals?.volume ?? item.total_volume ?? 0,
            total_rebate: totals?.commission ?? item.total_rebate ?? 0,
          };
          // todo check auto generated
          if (generateCode && generateCode.code === item.code) {
            code.isAutoGenerated = true;
          }
          return code;
        });

      const pinedItems: ReferralCodeType[] = [];
      const unpinedItems: ReferralCodeType[] = [...referralCodes];

      for (let i = 0; i < pinCodes.length; i++) {
        const code = pinCodes[i];
        const index = unpinedItems.findIndex((item) => item.code === code);
        if (index !== -1) {
          pinedItems.push({ ...unpinedItems[index], isPined: true });
          unpinedItems.splice(index, 1);
        }
      }

      // Add pinned items first, then unpinned items
      allCodes.push(...pinedItems, ...unpinedItems);
    }

    // Return undefined if no codes at all (maintains existing behavior)
    if (allCodes.length === 0) {
      return undefined;
    }

    return allCodes;
  }, [
    referralInfo?.referrer_info?.referral_codes,
    pinCodes,
    generateCode,
    multiLevelRebateInfo,
    multiLevelStatistics,
    singleLevelTotals,
  ]);

  return {
    copyCode,
    copyLink,
    editRate,
    editCode,
    setPinCode,
    codes,
  };
};
