import { useMemo } from "react";
import { RefferalAPI, useLocalStorage } from "@orderly.network/hooks";
import { modal } from "@orderly.network/ui";
import { useReferralContext } from "../../../provider";
import { copyText, generateReferralLink } from "../../../utils/utils";
import { EditCodeModal } from "./editCodeModal";
import { EditReferralRate } from "./editReferralRate";

type LegacyReferralCode = NonNullable<
  NonNullable<RefferalAPI.ReferralInfo["referrer_info"]>["referral_codes"]
>[number];

export type ReferralCodeType = LegacyReferralCode & {
  isPined?: boolean;
  isAutoGenerated?: boolean;
};

export type ReferralCodesReturns = {
  copyCode: (code: string) => void;
  copyLink: (code: string) => void;
  editRate: (code: ReferralCodeType) => void;
  editCode: (code: ReferralCodeType) => void;
  setPinCode: (code: string, del?: boolean) => void;
  codes?: ReferralCodeType[];
};

export const useReferralCodesScript = (): ReferralCodesReturns => {
  const { referralInfo, referralLinkUrl, mutate, generateCode } =
    useReferralContext();

  const copyLink = (code: string) => {
    copyText(generateReferralLink(referralLinkUrl, code));
  };
  const copyCode = (code: string) => {
    copyText(code);
  };
  const editRate = (code: ReferralCodeType) => {
    modal.show(EditReferralRate, { code: { ...code }, mutate });
  };

  const editCode = (code: ReferralCodeType) => {
    modal.show(EditCodeModal, {
      code: { ...code },
      successCallback: () => {
        mutate();
      },
    });
  };

  const [pinCodes, setPinCodes] = useLocalStorage<string[]>(
    "orderly_referral_codes",
    [] as string[],
  );
  const setPinCode = (code: string, del?: boolean) => {
    if (del) {
      const index = pinCodes.findIndex((item: string) => item === code);
      if (index !== -1) {
        pinCodes.splice(index, 1);
      }
    } else {
      pinCodes.splice(0, 0, code);
    }

    if (pinCodes.length > 6) {
      pinCodes.splice(pinCodes.length - 1, 1);
    }

    setPinCodes([...pinCodes]);
  };

  const codes = useMemo((): ReferralCodeType[] | undefined => {
    if (referralInfo?.referrer_info?.referral_codes) {
      const referralCodes: ReferralCodeType[] =
        referralInfo.referrer_info.referral_codes.map((item) => {
          const code: ReferralCodeType = {
            ...item,
          };
          // todo check auto generated
          if (generateCode && generateCode.code === item.code) {
            code.isAutoGenerated = true;
          }
          return code;
        });

      const pinedItems: ReferralCodeType[] = [];
      const unpinedItems: ReferralCodeType[] = [...referralCodes];

      for (let i = 0; i < pinCodes.length; i++) {
        const code = pinCodes[i];
        const index = unpinedItems.findIndex((item) => item.code === code);
        if (index !== -1) {
          pinedItems.push({ ...unpinedItems[index], isPined: true });
          unpinedItems.splice(index, 1);
        }
      }

      // Add pinned items first, then unpinned items
      const allCodes: ReferralCodeType[] = [...pinedItems, ...unpinedItems];

      // Return undefined if no codes at all (maintains existing behavior)
      if (allCodes.length === 0) {
        return undefined;
      }

      return allCodes;
    }

    // Return undefined if no codes at all (maintains existing behavior)
    return undefined;
  }, [referralInfo?.referrer_info?.referral_codes, pinCodes, generateCode]);

  return {
    copyCode,
    copyLink,
    editRate,
    editCode,
    setPinCode,
    codes,
  };
};
