import React, { FC, useCallback, useMemo, useState } from "react";
import {
  Flex,
  Text,
  Collapsible,
  CollapsibleContent,
  Box,
} from "@orderly.network/ui";

type FaqItem = {
  id: string;
  number: number;
  question: string;
  answer: string;
  expanded: boolean;
};

export const Faq = () => {
  const faqItemsData = useMemo<Omit<FaqItem, "expanded">[]>(() => {
    return [
      {
        id: "faq-1",
        number: 1,
        question: "What about this referral program?",
        answer:
          "This is a multi-level referral system that rewards you, the affiliate for growing the network. You earn a continuous share of the DEX revenue generated by every trader in your referral chain - not just those you invite directly. <br />This is a multilevel referral program designed to continuously reward you for expanding the network. You earn an ongoing share of the DEX revenue generated by every trader within your referral chain, extending beyond just the individuals you invite directly.",
      },
      {
        id: "faq-2",
        number: 2,
        question: "How are my commissions calculated? ",
        answer:
          "Your commissions are the difference between your assigned commission rate and the percentage you choose to pass on to your sub-affiliates. Importantly, your commission rate remains consistent regardless of how deep the referral chain goes.",
      },
      {
        id: "faq-3",
        number: 3,
        question:
          "How much commission can I share with my direct sub-affiliates?",
        answer:
          "The decision is entirely yours. You can assign any percentage, from 0% up to your maximum available commission rate, to your direct sub-affiliates to encourage their growth.",
      },
      {
        id: "faq-4",
        number: 4,
        question: "Where does the revenue come from?",
        answer:
          "Revenue comes from the trading fees generated by traders on the DEX. Whenever a trader in your chain makes a transaction, a portion of the fee is distributed from the top of the chain downwards based on the configured allocation.",
      },
      {
        id: "faq-5",
        number: 5,
        question: "How do I get my commissions?",
        answer:
          "Commissions are settled daily directly into your main trading account. You can view your overall commission earnings on the referral dashboard.",
      },
    ];
  }, []);

  // State to track which items are expanded
  const [expandedItems, setExpandedItems] = useState<Set<string>>(new Set());

  // Toggle expanded state
  const toggleItem = useCallback((id: string) => {
    setExpandedItems((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  }, []);

  const faqItems = useMemo(() => {
    return faqItemsData.map((item) => ({
      ...item,
      expanded: expandedItems.has(item.id),
    }));
  }, [faqItemsData, expandedItems]);

  return (
    <Box>
      {/* Title */}
      <Text className="oui-text-[32px]">FAQ</Text>

      {/* FAQ Items */}
      <Flex direction="column" itemAlign="stretch" gap={0}>
        {faqItems.map((item, index) => (
          <React.Fragment key={item.id}>
            <Collapsible
              open={item.expanded}
              onOpenChange={() => toggleItem(item.id)}
            >
              <Flex
                direction="column"
                className="oui-cursor-pointer oui-py-4"
                itemAlign="stretch"
                onClick={() => toggleItem(item.id)}
              >
                {/* Question row */}
                <Flex justify="between" itemAlign="center" gap={4}>
                  <Flex gap={2} itemAlign="center" className="oui-flex-1">
                    <Text size="2xl" weight="semibold">
                      {`${item.number}. ${item.question}`}
                    </Text>
                  </Flex>
                  <ChevronIcon expanded={item.expanded} />
                </Flex>

                {/* Answer (collapsible) */}
                <CollapsibleContent>
                  <Box
                    className="oui-pt-3 oui-text-base-contrast-54"
                    dangerouslySetInnerHTML={{ __html: item.answer }}
                  />
                </CollapsibleContent>
              </Flex>
            </Collapsible>

            {/* Divider (except for last item) */}
            {index < faqItems.length - 1 && (
              <div className="oui-my-4 oui-h-px oui-bg-line-6" />
            )}
          </React.Fragment>
        ))}
      </Flex>
    </Box>
  );
};

// Chevron icon component
const ChevronIcon: FC<{ expanded: boolean }> = ({ expanded }) => (
  <svg
    width="24"
    height="24"
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={`oui-transition-transform oui-duration-200 ${
      expanded ? "oui-rotate-180" : ""
    }`}
  >
    <path
      d="M4 6L8 10L12 6"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="oui-text-base-contrast-54"
    />
  </svg>
);
