export class MockData {
  static referralInfo = {
    referrer_info: {
      total_invites: 46,
      total_traded: 1168,
      total_referee_volume: 68068728.420962,
      referral_codes: [
        {
          code: "AAAA",
          max_rebate_rate: 0.6,
          referrer_rebate_rate: 0.15,
          referee_rebate_rate: 0.45,
          total_invites: 22,
          total_traded: 803,
        },
        {
          code: "AAAA1",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.15,
          referee_rebate_rate: 0.35,
          total_invites: 1,
          total_traded: 403,
        },
        {
          code: "AAAA2",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.19,
          referee_rebate_rate: 0.31,
          total_invites: 0,
          total_traded: 1,
        },
        {
          code: "AAAA3",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.28,
          referee_rebate_rate: 0.22,
          total_invites: 19,
          total_traded: 499,
        },
        {
          code: "AAAA4",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.3,
          referee_rebate_rate: 0.2,
          total_invites: 1,
          total_traded: 1,
        },
        {
          code: "AAAA5",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.3,
          referee_rebate_rate: 0.2,
          total_invites: 0,
          total_traded: 0,
        },
        {
          code: "AAAA6",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.18,
          referee_rebate_rate: 0.32,
          total_invites: 2,
          total_traded: 0,
        },
        {
          code: "AAAA7",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.15,
          referee_rebate_rate: 0.35,
          total_invites: 0,
          total_traded: 0,
        },
        {
          code: "AAAA8",
          max_rebate_rate: 0.5,
          referrer_rebate_rate: 0.42,
          referee_rebate_rate: 0.08,
          total_invites: 0,
          total_traded: 0,
        },
        {
          code: "AAAA9",
          max_rebate_rate: 0.6,
          referrer_rebate_rate: 0.31,
          referee_rebate_rate: 0.29,
          total_invites: 1,
          total_traded: 0,
        },
      ],
      total_referrer_rebate: 1779.135354,
      "1d_invites": 0,
      "7d_invites": 0,
      "30d_invites": 0,
      "1d_traded": 0,
      "7d_traded": 0,
      "30d_traded": 1693,
      "1d_referee_volume": 301239.33068,
      "7d_referee_volume": 2660996.5261,
      "30d_referee_volume": 19020775.540464,
      "1d_referrer_rebate": 4.522994,
      "7d_referrer_rebate": 43.675949,
      "30d_referrer_rebate": 615.208661,
    },
    referee_info: {
      referer_code: "AAAA001",
      referee_rebate_rate: 0.35,
      "1d_referee_rebate": 0,
      "7d_referee_rebate": 0,
      "30d_referee_rebate": 0,
      total_referee_rebate: 6.022652,
    },
  };
}
